export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';
export const GET_MOVIES = 'CONTENT.GET_MOVIES';
export const GET_MOVIES_SUCCESS = 'CONTENT.GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'CONTENT.GET_MOVIES_FAILURE';
